"""
LLM Wiki — a Markdown knowledge base for investment research.

Pages are stored in SQLite (``wiki_pages`` table), indexed into a dedicated
ChromaDB collection for semantic search, and can be generated by the LLM
either for a stock ticker (data-grounded research page) or for a financial
concept (explanatory page).

Usage::

    from src.wiki import WikiStore, WikiGenerator

    store = WikiStore()
    page = store.create_page(title="Sharpe Ratio", content="# Sharpe Ratio ...", category="concept")

    generator = WikiGenerator()
    draft = generator.generate_stock_page("AAPL")
    page = store.create_page(**draft)
"""

from src.wiki.generator import WikiGenerator
from src.wiki.store import WIKI_CATEGORIES, WikiStore, get_wiki_store

__all__ = ["WIKI_CATEGORIES", "WikiGenerator", "WikiStore", "get_wiki_store"]
